export const linksData = [
	{
		color: "black" as const,
		disabled: true,
		centered: true,
		noUnderline: true,
	},
	{
		color: "black" as const,
		disabled: true,
		centered: true,
		noUnderline: false,
	},
	{
		color: "black" as const,
		disabled: true,
		centered: false,
		noUnderline: true,
	},
	{
		color: "black" as const,
		disabled: true,
		centered: false,
		noUnderline: false,
	},
	{
		color: "black" as const,
		disabled: false,
		centered: true,
		noUnderline: true,
	},
	{
		color: "black" as const,
		disabled: false,
		centered: true,
		noUnderline: false,
	},
	{
		color: "black" as const,
		disabled: false,
		centered: false,
		noUnderline: true,
	},
	{
		color: "black" as const,
		disabled: false,
		centered: false,
		noUnderline: false,
	},
	{
		color: "grey" as const,
		disabled: true,
		centered: true,
		noUnderline: true,
	},
	{
		color: "grey" as const,
		disabled: true,
		centered: true,
		noUnderline: false,
	},
	{
		color: "grey" as const,
		disabled: true,
		centered: false,
		noUnderline: true,
	},
	{
		color: "grey" as const,
		disabled: true,
		centered: false,
		noUnderline: false,
	},
	{
		color: "grey" as const,
		disabled: false,
		centered: true,
		noUnderline: true,
	},
	{
		color: "grey" as const,
		disabled: false,
		centered: true,
		noUnderline: false,
	},
	{
		color: "grey" as const,
		disabled: false,
		centered: false,
		noUnderline: true,
	},
	{
		color: "grey" as const,
		disabled: false,
		centered: false,
		noUnderline: false,
	},
	{
		color: "blue" as const,
		disabled: true,
		centered: true,
		noUnderline: true,
	},
	{
		color: "blue" as const,
		disabled: true,
		centered: true,
		noUnderline: false,
	},
	{
		color: "blue" as const,
		disabled: true,
		centered: false,
		noUnderline: true,
	},
	{
		color: "blue" as const,
		disabled: true,
		centered: false,
		noUnderline: false,
	},
	{
		color: "blue" as const,
		disabled: false,
		centered: true,
		noUnderline: true,
	},
	{
		color: "blue" as const,
		disabled: false,
		centered: true,
		noUnderline: false,
	},
	{
		color: "blue" as const,
		disabled: false,
		centered: false,
		noUnderline: true,
	},
	{
		color: "blue" as const,
		disabled: false,
		centered: false,
		noUnderline: false,
	},
	{
		color: "white" as const,
		disabled: true,
		centered: true,
		noUnderline: true,
	},
	{
		color: "white" as const,
		disabled: true,
		centered: true,
		noUnderline: false,
	},
	{
		color: "white" as const,
		disabled: true,
		centered: false,
		noUnderline: true,
	},
	{
		color: "white" as const,
		disabled: true,
		centered: false,
		noUnderline: false,
	},
	{
		color: "white" as const,
		disabled: false,
		centered: true,
		noUnderline: true,
	},
	{
		color: "white" as const,
		disabled: false,
		centered: true,
		noUnderline: false,
	},
	{
		color: "white" as const,
		disabled: false,
		centered: false,
		noUnderline: true,
	},
	{
		color: "white" as const,
		disabled: false,
		centered: false,
		noUnderline: false,
	},
];
